services:
  postgres:
    image: postgres:17-alpine
    container_name: linkhub-postgres-dev

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vamsi123
      POSTGRES_DB: linkhub

    ports:
      # Port 5433 on host avoids conflicts with native Windows Postgres on 5432
      - "5433:5432"

    volumes:
      - linkhub_postgres_data:/var/lib/postgresql/data

    healthcheck:
      # FIXED: Changed -U to 'postgres' and -d to 'linkhub' to match your environment variables
      test: ["CMD-SHELL", "pg_isready -U postgres -d linkhub"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
          image: redis:8-alpine
          container_name: linkhub-redis-dev

          restart: unless-stopped

          ports:
            - "6379:6379"

          volumes:
            - linkhub_redis_data:/data

          command:
            - redis-server
            - --appendonly
            - "yes"

          healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 5

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: linkhub-minio-dev
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    command: server /data --console-address ":9001"
    volumes:
      - linkhub_minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-createbuckets:
    image: minio/mc
    container_name: linkhub-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadminpassword;
      /usr/bin/mc mb myminio/linkhub-avatars || true;
      /usr/bin/mc anonymous set private myminio/linkhub-avatars;
      exit 0;
      "

volumes:
  linkhub_postgres_data:
  linkhub_redis_data:
  linkhub_minio_data:

